/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.4 ../../public/models/FloorSharp.glb -t
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Suelo: THREE.Mesh
  }
  materials: {
    MaterialSuelo: THREE.MeshStandardMaterial
  }
}

export function FloorSharp(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/FloorSharp.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Suelo.geometry} material={materials.MaterialSuelo} position={[0, 1.3, 0]} />
    </group>
  )
}

useGLTF.preload('/models/FloorSharp.glb')
